import { StyleSheet } from 'react-native';

export const WelcomeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#3D5A3C',
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 40,
  },
  headerSection: {
    alignItems: 'center',
    marginBottom: 40,
  },
  logoPlaceholder: {
    width: 100,
    height: 100,
    borderRadius: 50,

    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  coderat: {
    width: 150,
    height : 150,
  }, 
  logoText: {
    fontSize: 50,
  },
  appTitle: {
    fontSize: 35,
    fontWeight: 'bold',
    color: '#D4A574',
    marginBottom: 10,
  },
  appSubtitle: {
    fontSize: 16,
    color: '#D4A574',
    opacity: 0.8,
    textAlign: 'center',
  },
  featureSection: {
    marginVertical: 20,
    flexDirection: 'row',
    justifyContent: 'space-around',
    gap: 12,
  },
  featureCard: {
    flex: 1,
    backgroundColor: 'rgba(212, 165, 116, 0.1)',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
  },
  featureIcon: {
    fontSize: 28,
    marginBottom: 8,
  },
  featureTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#D4A574',
    marginBottom: 4,
  },
  featureDescription: {
    fontSize: 11,
    color: '#D4A574',
    textAlign: 'center',
    opacity: 0.7,
  },
  buttonSection: {
    marginTop: 20,
    gap: 12,
  },
  primaryButton: {
    backgroundColor: '#D4A574',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    color: '#3D5A3C',
    fontSize: 16,
    fontWeight: '600',
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#D4A574',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: '#D4A574',
    fontSize: 16,
    fontWeight: '600',
  },
});

export const LogInStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#3D5A3C',
  },
  header: {
    backgroundColor: '#3D5A3C',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
  },
  backButton: {
    color: '#D4A574',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerIcon: {
    width: 48,
    height: 48,
    backgroundColor: '#D4A574',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerIconText: {
    fontSize: 28,
  },
  headerTitle: {
    color: '#D4A574',
    fontSize: 18,
    fontWeight: 'bold',
  },
  headerSubtitle: {
    color: '#D4A574',
    fontSize: 12,
    opacity: 0.7,
  },
  formContainer: {
    flex: 1,
    backgroundColor: '#F5F0E8',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginTop: 12,
  },
  formContent: {
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 24,
  },
  fieldGroup: {
    marginBottom: 24,
  },
  label: {
    color: '#3D5A3C',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: 'rgba(212, 165, 116, 0.3)',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 14,
    color: '#3D5A3C',
  },
  optionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  checkboxGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: '#3D5A3C',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#3D5A3C',
  },
  checkmark: {
    color: '#D4A574',
    fontSize: 14,
    fontWeight: 'bold',
  },
  checkboxLabel: {
    color: '#3D5A3C',
    fontSize: 13,
    opacity: 0.7,
  },
  forgotLink: {
    color: '#3D5A3C',
    fontSize: 13,
    textDecorationLine: 'underline',
  },
  loginButton: {
    backgroundColor: '#3D5A3C',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 16,
  },
  loginButtonText: {
    color: '#D4A574',
    fontSize: 16,
    fontWeight: '600',
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 16,
    gap: 12,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#3D5A3C',
    opacity: 0.2,
  },
  dividerText: {
    color: '#3D5A3C',
    fontSize: 12,
    opacity: 0.5,
  },
  googleButton: {
    borderWidth: 1,
    borderColor: 'rgba(61, 90, 60, 0.3)',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 16,
  },
  googleButtonText: {
    color: '#3D5A3C',
    fontSize: 14,
    fontWeight: '600',
  },
  signUpContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 16,
  },
  signUpText: {
    color: '#3D5A3C',
    fontSize: 13,
    opacity: 0.7,
  },
  signUpLink: {
    color: '#3D5A3C',
    fontSize: 13,
    textDecorationLine: 'underline',
    fontWeight: '600',
  },
});

export const SignUpStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#3D5A3C',
  },
  header: {
    backgroundColor: '#3D5A3C',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
  },
  backButton: {
    color: '#D4A574',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerIcon: {
    width: 48,
    height: 48,
    backgroundColor: '#D4A574',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerIconText: {
    fontSize: 28,
  },
  headerTitle: {
    color: '#D4A574',
    fontSize: 18,
    fontWeight: 'bold',
  },
  headerSubtitle: {
    color: '#D4A574',
    fontSize: 12,
    opacity: 0.7,
  },
  formContainer: {
    flex: 1,
    backgroundColor: '#F5F0E8',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginTop: 12,
  },
  formContent: {
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 24,
  },
  fieldGroup: {
    marginBottom: 20,
  },
  label: {
    color: '#3D5A3C',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: 'rgba(212, 165, 116, 0.3)',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 14,
    color: '#3D5A3C',
  },
  helperText: {
    color: '#3D5A3C',
    fontSize: 12,
    opacity: 0.6,
    marginTop: 6,
  },
  checkboxGroup: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginVertical: 16,
    gap: 10,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: '#3D5A3C',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
  },
  checkboxChecked: {
    backgroundColor: '#3D5A3C',
  },
  checkmark: {
    color: '#D4A574',
    fontSize: 14,
    fontWeight: 'bold',
  },
  checkboxLabel: {
    color: '#3D5A3C',
    fontSize: 13,
    opacity: 0.7,
    flex: 1,
    lineHeight: 18,
  },
  signUpButton: {
    backgroundColor: '#3D5A3C',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 8,
  },
  signUpButtonText: {
    color: '#D4A574',
    fontSize: 16,
    fontWeight: '600',
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 16,
    gap: 12,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#3D5A3C',
    opacity: 0.2,
  },
  dividerText: {
    color: '#3D5A3C',
    fontSize: 12,
    opacity: 0.5,
  },
  googleButton: {
    borderWidth: 1,
    borderColor: 'rgba(61, 90, 60, 0.3)',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  googleButtonText: {
    color: '#3D5A3C',
    fontSize: 14,
    fontWeight: '600',
  },
  loginLinkContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 16,
  },
  loginLinkText: {
    color: '#3D5A3C',
    fontSize: 13,
    opacity: 0.7,
  },
  loginLink: {
    color: '#3D5A3C',
    fontSize: 13,
    textDecorationLine: 'underline',
    fontWeight: '600',
  },
});

export const ProfileStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#3D523B' },
  scrollContent: { paddingBottom: 100 },
  header: { flexDirection: 'row', justifyContent: 'space-between', padding: 20, alignItems: 'center' },
  backButton: { flexDirection: 'row', alignItems: 'center' },
  headerText: { color: 'white', fontSize: 18, marginLeft: 5 },
  currencyContainer: { flexDirection: 'row', alignItems: 'center' },
  currencyText: { color: 'white', marginLeft: 5, fontWeight: 'bold' },
  profileSection: { alignItems: 'center', marginTop: 10 },
  avatarContainer: { width: 120, height: 120, position: 'relative' },
  avatarCircle: { width: '100%', height: '100%', borderRadius: 60, backgroundColor: '#D9A066' },
  levelBadge: { position: 'absolute', bottom: 0, right: 0, backgroundColor: '#D9A066', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, borderWidth: 2, borderColor: '#3D523B' },
  levelText: { color: 'white', fontSize: 12, fontWeight: 'bold' },
  userName: { color: 'white', fontSize: 24, fontWeight: 'bold', marginTop: 15 },
  userTitle: { color: '#A1A1A1', fontSize: 16 },
  statsRow: { flexDirection: 'row', justifyContent: 'space-around', marginVertical: 25, paddingHorizontal: 20 },
  statBox: { alignItems: 'center' },
  statValueRow: { flexDirection: 'row', alignItems: 'center' },
  statValue: { color: 'white', fontSize: 20, fontWeight: 'bold', marginLeft: 5 },
  statLabel: { color: '#A1A1A1', fontSize: 12, marginTop: 4 },
  divider: { width: 1, height: 40, backgroundColor: '#556B53' },
  workoutCard: { backgroundColor: 'white', borderTopLeftRadius: 30, borderTopRightRadius: 30, padding: 25, flex: 1, minHeight: 400 },
  workoutHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  workoutTitle: { color: '#E0E0E0', fontSize: 18, fontWeight: '600' },
  completionStatus: { flexDirection: 'row', alignItems: 'center' },
  completionText: { color: '#A1A1A1', fontSize: 14 },
  dateRibbon: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 25 },
  dateItem: { backgroundColor: '#F2F2F2', padding: 15, borderRadius: 15, alignItems: 'center', width: '22%' },
  activeDateItem: { backgroundColor: '#D9A066' },
  dateText: { color: '#888', fontSize: 12 },
  dateNumber: { color: '#444', fontSize: 18, fontWeight: 'bold' },
  activeDateText: { color: 'white' },
  taskItem: { backgroundColor: '#F9F9F4', padding: 18, borderRadius: 15, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  taskLeft: { flexDirection: 'row', alignItems: 'center' },
  checkbox: { width: 20, height: 20, borderRadius: 5, borderWidth: 1, borderColor: '#D9A066', marginRight: 15 },
  taskTitle: { color: '#666', fontSize: 16 },
  taskReward: { flexDirection: 'row', alignItems: 'center' },
  rewardText: { color: '#888', marginLeft: 5 },
  bottomNav: { position: 'absolute', bottom: 0, width: '100%', height: 90, backgroundColor: 'white', flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingBottom: 10 },
  navItem: { alignItems: 'center' },
  navLabel: { fontSize: 10, color: '#A1A1A1', marginTop: 4 },
  activeNavCircle: { width: 60, height: 60, borderRadius: 30, backgroundColor: '#FDF5E6', justifyContent: 'center', alignItems: 'center', marginBottom: 40, borderWidth: 2, borderColor: '#D9A066' }
});
